export const ROUTE = {
  ROOT: '/',
  HOME: '/home',
  AGREEMENTS: '/agreements',
  AGREEMENT_DETAILS: '/agreement-details/:id',
  AUTH_CALLBACK: '/auth-callback',
};

export const API_LINKS = {
  AUTHORIZE: process.env.REACT_APP_API_AUTHORIZE ?? "AUTHORIZE",
  AUTHORIZE_TEST_1: process.env.REACT_APP_API_AUTHORIZE_TEST_1 ?? "AUTHORIZE_TEST_1",
  AUTHORIZE_TEST_2: process.env.REACT_APP_API_AUTHORIZE_TEST_2 ?? "AUTHORIZE_TEST_2",
  LOGOUT: process.env.REACT_APP_API_LOGOUT ?? "LOGOUT",
  GET_AGREEMENTS: process.env.REACT_APP_API_GET_AGREEMENTS ?? "GET_AGREEMENTS",
};

export const LINKS = {
  API_HOME_PAGE: process.env.REACT_APP_LINKS_API_HOME_PAGE ?? "API_HOME_PAGE",
  GITHUB: process.env.REACT_APP_LINKS_GITHUB ?? "GITHUB",
  ACC_BRANDS_CREATE: process.env.REACT_APP_LINKS_ACC_BRANDS_CREATE ?? "ACC_BRANDS_CREATE",
  ACC_BRANDS_LIST: process.env.REACT_APP_LINKS_ACC_BRANDS_LIST ?? "ACC_BRANDS_LIST",
  USE_CASES: process.env.REACT_APP_LINKS_USE_CASES ?? "USE_CASES",
};
